permissions:
  contents: read

name: SDK Android Build

# Perform an Android build, create a release, and attach build
# artifacts to the release when a Vulkan SDK tag is pushed. The
# Vulkan SDK does not include binaries for Android, so we publish
# them here to provide Android binaries built from the same source
# used to build the Vulkan SDK.
#
# The tag needs to be pushed by name, as `git push --tags` to push all
# tags does not appear to trigger the action.
#
# The Vulkan SDK release process is similar to the following:
# 1. Add a lightweight tag with the sdk version string.
#        git tag vulkan-sdk-1.2.141.0
# 3. Push the tag to GitHub.
#        git push origin vulkan-sdk-1.2.141.0

on:
  push:
    tags:
      - vulkan-sdk-*

jobs:
  android:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Android Release/Debug",
            os: ubuntu-latest,
            artifact: "gfxreconstruct-android"
          }
    steps:
    - name: Clone repository
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      with:
        persist-credentials: false
        submodules: 'recursive'
    - name: Set up Java
      uses: "actions/setup-java@d7793b545071e98d581d3bf084a51c3213318a07"
      with:
        java-version: 17
        distribution: "temurin"
    - name: Gradle build
      run: |
        cd android
        sh gradlew assembleRelease assembleDebug
    - name: Prepare artifacts
      run: |
        mkdir gfxreconstruct-dev
        mkdir gfxreconstruct-dev/layer
        mkdir gfxreconstruct-dev/tools
        cp LICENSE.txt gfxreconstruct-dev/
        cp LICENSE_ThirdParty.txt gfxreconstruct-dev/
        cp USAGE_android.md gfxreconstruct-dev/
        cp layer/vk_layer_settings.txt gfxreconstruct-dev/
        cp -r android/layer/build/intermediates/cxx/RelWithDebInfo/*/obj/arm64-v8a gfxreconstruct-dev/layer/
        cp android/tools/replay/build/outputs/apk/debug/replay-debug.apk gfxreconstruct-dev/tools/
        cp android/scripts/gfxrecon.py gfxreconstruct-dev/tools/
    - name: Upload artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: ${{ matrix.config.artifact }}
        path: ./gfxreconstruct-dev

  release:
    permissions:
      contents: write
    name: Create Release for Tag
    runs-on: ubuntu-latest
    needs: android
    steps:
    - name: Get sdk version string
      id: get_sdk_version
      env:
        GITHUB_REF: ${{ github.ref }}
      run: |
        sdk_version=`echo "$GITHUB_REF" | cut -d "-" -f 2`
        echo "::set-output name=sdk_version::$sdk_version"
    - name: Create release
      id: create_release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SDK_VERSION: ${{ steps.get_tag_body.outputs.sdk_version }}
        REF_NAME: ${{ github.ref_name }}
      run: |
        cat << MESSAGE > release_message.txt
Android binaries to compliment the desktop binaries distributed with the Vulkan ${SDK_VERSION} SDK.
MESSAGE
        gh release create "${REF_NAME}" \
          --title "Android binaries for ${SDK_VERSION} SDK release" \
          --notes-file release_message.txt \
          || echo "Release might already exist"

          Build Info:
          - Android SDK Version: 27 (Android 8.1)
          - Android NDK Version: 21.3.6528147 (r21d)
        draft: false
        prerelease: false
    - name: Get release URL
      env:
        UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
      run: |
        echo "$UPLOAD_URL" > ./release_url
    - name: Upload release URL
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: release_url
        path: ./release_url

  publish:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    needs: release
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Upload Android Release Tar Gzip Artifact",
            os: ubuntu-latest,
            artifact: "gfxreconstruct-android",
            command: "tar czf",
            suffix: "android.tar.gz",
            type: "application/x-gtar"
          }
        - {
            name: "Upload Android Release Zip Artifact",
            os: ubuntu-latest,
            artifact: "gfxreconstruct-android",
            command: "zip -r",
            suffix: "android.zip",
            type: "application/zip"
          }
    steps:
    - name: Get tag name
      id: get_tag_name
      env:
        GITHUB_REF: ${{ github.ref }}
      run: |
        tag_name=`echo "$GITHUB_REF" | cut -d "/" -f 3`
        echo "::set-output name=tag_name::$tag_name"
    - name: Download artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
      with:
        name: ${{ matrix.config.artifact }}
        path: ./gfxreconstruct-${{ steps.get_tag_name.outputs.tag_name }}
    - name: Make release artifacts
      env:
        TAG_NAME: ${{ steps.get_tag_name.outputs.tag_name }}
        CONFIG_COMMAND: ${{ matrix.config.command }}
        CONFIG_SUFFIX: ${{ matrix.config.suffix }}
      run: |
        $CONFIG_COMMAND gfxreconstruct-$TAG_NAME-$CONFIG_SUFFIX gfxreconstruct-$TAG_NAME
    - name: Download release URL
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
      with:
        name: release_url
        path: ./
    - name: Set upload URL
      id: set_upload_url
      run: |
        upload_url=`cat ./release_url`
        echo "::set-output name=upload_url::$upload_url"
    - name: Upload release artifacts
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: ${{ steps.get_tag_name.outputs.tag_name }}
        SUFFIX: ${{ matrix.config.suffix }}
      run: |
        gh release upload "${TAG_NAME}" "./gfxreconstruct-${TAG_NAME}-${SUFFIX}" --clobber
